# Generated by Django 3.1.7 on 2022-08-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okra_server', '0005_auto_20220704_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='instructions_after',
            field=models.TextField(null=True),
        ),
    ]
