# Generated by Django 3.1.7 on 2022-08-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okra_server', '0006_task_instructions_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
