# Generated by Django 3.1.7 on 2023-01-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okra_server', '0008_auto_20230109_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='label',
            field=models.CharField(blank=True, default='unlabeled', max_length=50),
        ),
    ]
