# Generated by Django 3.1.7 on 2023-01-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okra_server', '0009_participant_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['label']},
        ),
        migrations.AlterField(
            model_name='taskrating',
            name='rating_type',
            field=models.CharField(choices=[('emoticon', 'Emoticons (right-positive)'), ('emoticon-reversed', 'Emoticons (left-positive)'), ('radio', 'Radio buttons'), ('radio-vertical', 'Radio buttons (vertical)'), ('slider', 'Slider')], max_length=50),
        ),
    ]
