# Generated by Django 3.1.7 on 2023-01-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okra_server', '0011_auto_20230120_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='active',
            new_name='visible',
        ),
    ]
