# Generated by Django 5.1.1 on 2025-06-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okra_server', '0013_auto_20230123_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrating',
            name='options',
            field=models.JSONField(null=True),
        ),
    ]
