repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: ^okra_server/migrations/
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^okra_server/migrations/
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^okra_server/migrations/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: \.html$
  - repo: https://github.com/aneustroev/jinjalint
    rev: 65d13cb
    hooks:
      - id: jinjalint
        types: [file]
        files: \.html$
