# Generated by Django 3.1.7 on 2021-03-17 10:15

from django.db import migrations, models
import django.db.models.deletion
import functools
import okra_server.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('cloze', 'Cloze test'), ('lexical-decision', 'Lexical decision'), ('picture-naming', 'Picture-naming'), ('question-answering', 'Question answering')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('cover_image_url', models.URLField(null=True)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('device_key', models.CharField(max_length=24, null=True)),
                ('registration_key', models.CharField(default=functools.partial(okra_server.models._random_key, *(24,), **{}), max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('data', models.JSONField()),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='okra_server.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('rating_type', models.CharField(choices=[('emoticon', 'Emoticons'), ('radio', 'Radio buttons'), ('slider', 'Slider')], max_length=50)),
                ('low_extreme', models.TextField(null=True)),
                ('high_extreme', models.TextField(null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='okra_server.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('results', models.JSONField(null=True)),
                ('started_time', models.DateTimeField(null=True)),
                ('finished_time', models.DateTimeField(null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='okra_server.participant')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='okra_server.task')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='practice_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_experiment', to='okra_server.task'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(fields=('participant', 'task'), name='unique_assignment'),
        ),
    ]
