# Generated by Django 3.1.7 on 2021-03-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okra_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
