# Generated by Django 3.1.7 on 2021-03-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okra_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='task_type',
            field=models.CharField(choices=[('cloze', 'Cloze test'), ('lexical-decision', 'Lexical decision'), ('n-back', 'n-back'), ('picture-naming', 'Picture-naming'), ('question-answering', 'Question answering'), ('reaction-time', 'Reaction time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taskrating',
            name='rating_type',
            field=models.CharField(choices=[('emoticon', 'Emoticons (right-positive)'), ('emoticon-reversed', 'Emoticons (left-positive)'), ('radio', 'Radio buttons'), ('slider', 'Slider')], max_length=50),
        ),
    ]
