# Generated by Django 3.1.7 on 2021-03-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okra_server', '0002_auto_20210330_2014'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskassignment',
            name='unique_assignment',
        ),
    ]
