# Generated by Django 3.1.7 on 2021-03-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okra_server', '0002_task_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='practice_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_experiment', to='okra_server.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='okra_server.experiment'),
        ),
    ]
