# Generated by Django 3.1.7 on 2021-04-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okra_server', '0003_auto_20210331_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='task_type',
            field=models.CharField(choices=[('cloze', 'Cloze test'), ('lexical-decision', 'Lexical decision'), ('n-back', 'n-back'), ('picture-naming', 'Picture-naming'), ('question-answering', 'Question answering'), ('reaction-time', 'Reaction time'), ('simon-game', 'Simon game')], max_length=50),
        ),
    ]
