# Generated by Django 3.1.7 on 2021-03-11 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('okra_server', '0003_auto_20210305_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrating',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
