name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Static analysis & unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
          pip install -r web/requirements.dev.txt
      - run: pre-commit run -a
      - run: pytest --cov-report xml --cov okra_server
        working-directory: ./web
      - uses: codecov/codecov-action@v1
        with:
          files: web/coverage.xml
          fail_ci_if_error: true
